### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#50]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:43 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/50_

---

Run tests etc. Probably use hosted Jenkins on Cloudbees.

**Comment by nmarquesantos** [comment]
So I've had a look at Jenkins and Travis.

For Cloudbees Jenkins, I couldn't find a free solution except for a dockerized and for our own hosted Jenkins platform.

For the Cloud, it seems only the Jenkins Enterprise is now available, with a trial period of 14 days.

Travis is still free ofc, so I'll give it a go.

However, I can start by just using my forked repo (as I need to have some minor configuration files for travis) and then make a pull request.

Travis will then need to be configured to reflect to the repo tesco/mewbase instead of nmarquesantos/mewbase.

Or we should add an organization there.

**Comment by purplefox** [comment]
Sounds great.. let's give Travis a spin.

**Comment by fbalicchia** [comment]
Hi, 
I've read only now. 
I' ve complete basic setup for build and deploy with Travis. 
Jar and Deb file created are automatically upload on Github with Oauth token.

@nmarquesantos if you have already done it np I'll close my branch. Otherwise I' ll open a push request
Thanks

**Comment by nmarquesantos** [comment]
@fbalicchia go ahead, I was only going to start work on it now :)

cheers
